import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { DirectoryProvider } from '@/providers/DirectoryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ATM-TOTAL DATA',
  description: 'Generated by 3S ITALO',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <DirectoryProvider>
          {children}
        </DirectoryProvider>
      </body>
    </html>
  )
}
